### ISSUE TITLE
Autocorrelación Espacial de tu Variable

### ISSUE THREAD

**Issue by MirelSIG** [maestria-geotel-master/material-de-apoyo#2]
@geofis Las lineas de comando 233 (hoyod) y 251 (mi turno), referidas a   st_drop_geometry(), generan el error inicial:
Error in st_geometry.sf(x) : 
  attr(obj, "sf_column") does not point to a geometry column.
Did you rename it, without setting st_geometry(obj) <- "newname"?
Posteriormente:
Error in select(-muestra) : object 'muestra' not found

**Comment by MirelSIG** [comment]
Resuelto

**Comment by geofis** [comment]
Ah, vaya, qué bueno, resolviendo por tu cuenta. Genial
